2018-09-20 16:21:34,876 ERROR: Exception on / [GET] [in /Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/app/routes.py", line 33, in index
    prev_url=prev_url)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/xiaoyongqiang/python/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 35, in top-level template code
    {% block scripts %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 36, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2018-09-20 16:21:40,441 ERROR: Exception on / [GET] [in /Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/app/routes.py", line 33, in index
    prev_url=prev_url)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/xiaoyongqiang/python/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 35, in top-level template code
    {% block scripts %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 36, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2018-09-20 16:22:11,079 ERROR: Exception on / [GET] [in /Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/app/routes.py", line 33, in index
    prev_url=prev_url)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoyongqiang/python/myblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/xiaoyongqiang/python/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 35, in top-level template code
    {% block scripts %}
  File "/Users/xiaoyongqiang/python/myblog/app/templates/base.html", line 36, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
